#!/bin/bash
sudo dpkg --purge telnetd
sudo dpkg --purge logkeys
sudo dpkg --purge Hydra
sudo dpkg --purge fakeroot
sudo dpkg --purge Crack
sudo dpkg --purge crack
sudo dpkg --purge medusa
sudo dpkg --purge nikto
sudo dpkg --purge tightvnc
sudo dpkg --purge aMule
sudo dpkg --purge angryipscanner
sudo dpkg --purge arp-scan
sudo dpkg --purge cmospwd
sudo dpkg --purge cupp3
sudo dpkg --purge deluge
sudo dpkg --purge doomsday
sudo dpkg --purge dsniff
sudo snap remove endlesssky
sudo dpkg --purge ettercap-text-only
sudo dpkg --purge ettercap-graphical
sudo dpkg --purge fcrackzip
sudo dpkg --purge freeciv
sudo dpkg --purge goldeneye
sudo dpkg --purge heartbleeder
sudo dpkg --purge hunt
sudo dpkg --purge hydra
sudo dpkg --purge john
sudo dpkg --purge kismet
sudo dpkg --purge knocker
sudo dpkg --purge linuxdcpp
sudo dpkg --purge minetest
sudo dpkg --purge nbtscan
sudo dpkg --purge nmapsi4
sudo dpkg --purge nmap
sudo dpkg --purge zenmap
sudo snap remove openra
sudo dpkg --purge ophcrack
sudo dpkg --purge p0f
sudo dpkg --purge packit
sudo dpkg --purge pixeldungeon
sudo dpkg --purge pompem
sudo dpkg --purge pnscan
sudo dpkg --purge reaver
sudo dpkg --purge rfdump
sudo dpkg --purge remmina
sudo dpkg --purge tcpspray
sudo dpkg --purge themole
sudo dpkg --purge wireshark
sudo dpkg --purge xprobe
sudo dpkg --purge yersinia
sudo dpkg --purge zangband
