#!/bin/bash

sudo yum remove telnet-server
sudo yum remove logkeys
sudo yum remove hydra
sudo yum remove fakeroot
sudo yum remove crack
sudo yum remove medusa
sudo yum remove nikto
sudo yum remove tigervnc-server
sudo yum remove amule
sudo yum remove angryipscanner
sudo yum remove arp-scan
sudo yum remove cmospwd
sudo yum remove cupp
sudo yum remove deluge
sudo yum remove doomsday
sudo yum remove dsniff
sudo snap remove endlesssky
sudo yum remove ettercap-text-only
sudo yum remove ettercap-graphical
sudo yum remove fcrackzip
sudo yum remove freeciv
sudo yum remove goldeneye
sudo yum remove heartbleeder
sudo yum remove hunt
sudo yum remove hydra
sudo yum remove john
sudo yum remove kismet
sudo yum remove knocker
sudo yum remove linuxdcpp
sudo yum remove minetest
sudo yum remove nbtscan
sudo yum remove nmap-frontend
sudo yum remove nmap
sudo yum remove zenmap
sudo snap remove openra
sudo yum remove ophcrack
sudo yum remove p0f
sudo yum remove packit
sudo yum remove pixeldungeon
sudo yum remove pompem
sudo yum remove pnscan
sudo yum remove reaver
sudo yum remove rfdump
sudo yum remove remmina
sudo yum remove tcpspray
sudo yum remove themole
sudo yum remove wireshark
sudo yum remove xprobe
sudo yum remove yersinia
sudo yum remove zangband
